import { defineConfig } from 'tsdown';

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm', 'cjs'],
  // Types are generated by dts-bundle-generator (see the build:types script):
  // tsdown's own dts step loads native binaries that Windows Smart App Control blocks.
  dts: false,
  sourcemap: true,
  clean: true,
  target: 'es2020',
});
